name: "CI"

on:
  push:
    paths-ignore:
      - "README.md"
      - "LICENSE"
      - ".editorconfig"
      - ".gitignore"
  pull_request:

jobs:
  unittest:
    timeout-minutes: 31
    runs-on: ubuntu-latest
    name: "Unit Tests"

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Test  Package
      run: go test -v "./go-zabbix/.."

    - name: Test Types Package
      run: go test -v "./types/..."

  integration:
    timeout-minutes: 31
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        zabbix:
          - version: "4.0"
            suffix: "-latest"
          - version: "5.0"
            suffix: "-latest"
          - version: "6.0"
            suffix: "-latest"
          - version: "6.2"
            suffix: "-latest"
          - version: "6.4"
            suffix: "-latest"
          - version: "trunk" # will become 7.0
            suffix: ""

    name: "Zabbix ${{ matrix.zabbix.version }} Integration Tests"

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Start containers
      run: docker compose -f "docker-compose.yml" up -d
      env:
        ZBX_VERSION: "${{ matrix.zabbix.version }}"
        ZBX_VERSION_SUFFIX: "${{ matrix.zabbix.suffix }}"

    - name: Wait for Zabbix server to become available
      uses: iFaxity/wait-on-action@v1.1.0
      with:
        resource: tcp:localhost:10051
        timeout: 900000
        interval: 10000
        delay: 60000
        log: true

    - name: Test
      run: go test -v "./test/integration/..."

    - name: Stop containers
      if: always()
      run: docker compose -f "docker-compose.yml" down --volumes
